name: v8
services:
    ultralytics:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        container_name: v8
        privileged: true
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
            - DISPLAY=unix$DISPLAY
            - GDK_SCALE
            - GDK_DPI_SCALE
        network_mode: host
        devices:
            - /dev/video0:/dev/video0
            - /dev/video1:/dev/video1
            - /dev/video2:/dev/video2
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        image: ohin112/ultralytics:noetic-cpu
        command: bash